name: example
description: Example of simple_calendar package.
homepage: thecodebrothers.pl

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  simple_calendar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  tcb_dcm_presets: ^1.0.4

dependency_overrides:
  simple_calendar:
    path: ../

flutter:
  uses-material-design: true
