name: simple_calendar
description: Simple Calendar package for displaying a calendar with events
version: 0.0.1
repository: https://github.com/thecodebrothers/simple-calendar

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  intl: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  tcb_dcm_presets: ^1.0.4
